#!/usr/bin/env node
/**
 * Generates src/icons/library.ts from the raw SVG sources of the icon
 * sets Shear ships with:
 *
 *   - Lucide            (stroke icons, 24x24)
 *   - Heroicons outline (stroke icons, 24x24)
 *   - Heroicons solid   (fill icons, 24x24)
 *
 * Usage:  node scripts/gen-icons.mjs /path/to/lucide-main /path/to/heroicons-master
 *
 * Every icon is normalised to a standalone `<svg>` string that uses
 * `currentColor`, so the editor can tint an icon by string replacement.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const [lucideDir, heroDir] = process.argv.slice(2)
if (!lucideDir || !heroDir) {
  console.error('usage: node gen-icons.mjs <lucide-repo> <heroicons-repo>')
  process.exit(1)
}

/** Reduce an svg file to a single line, normalised to currentColor. */
function normalize(raw) {
  let s = raw.replace(/\s+/g, ' ').trim()
  // drop comments and xml prologues
  s = s.replace(/<!--.*?-->/g, '').replace(/<\?xml.*?\?>/g, '')
  // strip width/height so the icon scales to its container
  s = s.replace(/(<svg[^>]*)\swidth="[^"]*"/, '$1').replace(/(<svg[^>]*)\sheight="[^"]*"/, '$1')
  // force currentColor so the editor can tint
  s = s.replace(/stroke="(?!(?:none|currentColor))[^"]*"/g, 'stroke="currentColor"')
  s = s.replace(/fill="(?!(?:none|currentColor))[^"]*"/g, 'fill="currentColor"')
  return s
}

const icons = []

function addSet(set, dir) {
  const files = readdirSync(dir).filter((f) => f.endsWith('.svg')).sort()
  for (const f of files) {
    const name = f.replace(/\.svg$/, '')
    icons.push({ set, name, svg: normalize(readFileSync(join(dir, f), 'utf8')) })
  }
  console.log(`${set}: ${files.length} icons`)
}

addSet('lucide', join(lucideDir, 'icons'))
addSet('heroicons-outline', join(heroDir, 'optimized', '24', 'outline'))
addSet('heroicons-solid', join(heroDir, 'optimized', '24', 'solid'))

const out = `// GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// ${icons.length} icons from Lucide + Heroicons, normalised to currentColor.

export interface IconDef {
  /** icon set the glyph comes from */
  set: string
  /** kebab-case name, also used for search */
  name: string
  /** standalone <svg> string using currentColor */
  svg: string
}

export const ICON_SETS = ['lucide', 'heroicons-outline', 'heroicons-solid'] as const

export const ICONS: IconDef[] = [
${icons.map((i) => `  { set: '${i.set}', name: '${i.name}', svg: ${JSON.stringify(i.svg)} },`).join('\n')}
]
`

writeFileSync(new URL('../src/icons/library.ts', import.meta.url), out)
console.log(`wrote src/icons/library.ts (${icons.length} icons, ${(out.length / 1024).toFixed(0)} KB)`)
